name: Linting

on: 
  push:
    branches: "*"
  pull_request:
      branches: dev, main

env:
  PYTHON_VERSION: "3.12"

jobs:
  pylint_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files 'src/*.py')
